apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: monitoring
spec:
  route:
    receiver: 'email'
    repeatInterval: 30m
    routes:
    - matchers:
      - name: alertname
        value: HostHighCpuLoad
    - matchers:
      - name: alertname
        value: KubernetesPodCrashLooping
  receivers:
    - name: 'email'
      emailConfigs:
      - to: 'julien.avezou@gmail.com'
        from: 'julien.avezou@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        authUsername: 'julien.avezou@gmail.com'
        authIdentity: 'julien.avezou@gmail.com'
        authPassword:
          name: gmail-auth
          key: password
